using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class enemyScript : MonoBehaviour
{
    Rigidbody rb;
    [Header("Movement")]
    public float moveSpeed;

    public GameObject player;
    // Start is called before the first frame update
    void Start()
    {
        rb = GetComponent<Rigidbody>();
        player = GameObject.Find("PLAYER");
    }

    // Update is called once per frame
    void Update()
    {
        Vector3 lookDirection = (player.transform.position - transform.position).normalized;
        rb.AddForce(lookDirection * moveSpeed);

        // Resets enemy if they are out of bounds
        if (transform.position.y < -38f)
        {
            Destroy(gameObject);
        }
    }
}
